# my-istio-chart/templates/gateway.yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: istio-ingress
spec:
  selector:
    istio: ingress
  servers:
  - port:
      number: {{ .Values.gateway.port }}
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.virtualservice.name }}
  namespace: istio-ingress
spec:
  hosts:
  - "{{ .Values.virtualservice.host }}"
  gateways:
  - {{ .Values.virtualservice.gateway }}
  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
      #  host: {{ .Values.virtualservice.destination.host }}
        host: test-ns-hello-world.test-ns.svc.cluster.local
        port:
          number: {{ .Values.virtualservice.destination.port }}


